name: Setup
description: checkout and install dependencies

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 8.6.2
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        check-latest: true
        cache: 'pnpm'
    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
